
.trigger {
  padding                : 0 16px;
  cursor                 : pointer;
  font-size              : 18px;
}

.avatar{

      position           : relative;
      display            : inline-block;
      width              : 40px;
      line-height        : 1;
      border-radius      : 500px;
      white-space        : nowrap;
      font-weight        : bold;
      img{
            border-radius : 500px;
            width         : 100%;
            vertical-align: middle;
      }

       
      i{
        position: absolute;
        left: 0;
        top: 0;
        width: 10px;
        height: 10px;
        margin: 1px;
        border-width: 2px;
        border-style: solid;
        border-radius: 100%;

       
        
      }

       .on {
            background-color: #6cc788;
       }
       .bottom {
          left: auto;
          top: auto;
          bottom: 0;
          right: 0;
      }
}


